In [1]:
!! cd

['C:\\Users\\nagal\\demo\\diabetes']

# Classification Case Study

# import libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(style = "white")

# Load data from final train csv

In [3]:
train = pd.read_csv("final_train.csv")

In [4]:
train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35       31  33.6   
1            1       85             66             29       31  26.6   
2            8      183             64             23       31  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  InsulinLog  
0                     0.627   50        1    3.433987  
1                     0.351   31        0    3.433987  
2                     0.672   32        1    3.433987  
3                     0.167   21        0    4.543295  
4                     2.288   33        1    5.123964

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
 9   InsulinLog                768 non-null    float64
dtypes: float64(3), int64(7)
memory usage: 60.1 KB


In [6]:
X = train.drop(columns = ["Outcome"])
y = train.Outcome

In [7]:
X.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'InsulinLog'],
      dtype='object')

In [8]:
X.shape

(768, 9)

# Split data into train and test

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [10]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [11]:
def print_scores(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    tn = cm[0, 0]
    tp = cm[1, 1]
    fp = cm[0, 1]
    fn = cm[1, 0]
    print(f"Overall Accuracy                           :{(tp + tn) / (tp + tn + fp + fn):.2f}")
    print(f"Precision of Positive cases                :{tp / (tp + fp):.2f}")
    print(f"Precision of Negative cases                :{tn / (tn + fn):.2f}")
    print(f"Positive Recall or TPR or Sensitivity      :{tp / (tp + fn):.2f}")
    print(f"Negative Recall or FPR or Specificity      :{tn / (tn + fp):.2f}")

# Logistic Regression

In [12]:
# IMPORTING PACKAGES LOGISTICREGRESSION AND EVALUATION
from sklearn.linear_model import LogisticRegression

In [13]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)

StandardScaler()

In [14]:
X_train_scaled = ss.transform(X_train)
X_test_scaled = ss.transform(X_test)

In [15]:
# LOGISTIC REGRESSION - TRAIN MODEL
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [16]:
# CHECK MODEL PERFORMANCE WITH TRAIN DATA
model.score(X_train_scaled, y_train)

0.7746741154562383

In [17]:
y_pred = model.predict(X_test_scaled)

In [18]:
accuracy_score(y_test, y_pred)

0.7792207792207793

In [19]:
confusion_matrix(y_test, y_pred)

array([[141,  16],
       [ 35,  39]], dtype=int64)

In [20]:
print_scores(y_test, y_pred)

Overall Accuracy                           :0.78
Precision of Positive cases                :0.71
Precision of Negative cases                :0.80
Positive Recall or TPR or Sensitivity      :0.53
Negative Recall or FPR or Specificity      :0.90


# Display classification_report

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.90      0.85       157
           1       0.71      0.53      0.60        74

    accuracy                           0.78       231
   macro avg       0.76      0.71      0.73       231
weighted avg       0.77      0.78      0.77       231



In [22]:
model.coef_

array([[ 0.31202607,  1.16780617, -0.22130256, -0.0209865 , -0.11143863,
         0.71702197,  0.24532108,  0.26334284, -0.04210537]])

In [23]:
model.intercept_

array([-0.79777035])

In [24]:
y_pred_prob = model.predict(X_test_scaled)

In [25]:
y_pred[5:10]

array([0, 1, 1, 0, 0], dtype=int64)

In [26]:
y_pred_prob[5:10]

array([0, 1, 1, 0, 0], dtype=int64)

In [27]:
y_pred_prob[5:10], y_pred[5:10]

(array([0, 1, 1, 0, 0], dtype=int64), array([0, 1, 1, 0, 0], dtype=int64))

In [28]:
y_pred_prob[0:5], y_pred[0:5]

(array([1, 0, 0, 1, 0], dtype=int64), array([1, 0, 0, 1, 0], dtype=int64))

# Decision Tree

In [29]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
model = DecisionTreeClassifier(max_depth = 5)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5)

In [36]:
model.score(X_train, y_train)

0.8324022346368715

In [39]:
y_train_pred = model.predict(X_train)

In [40]:
print_scores(y_train, y_train_pred)

Overall Accuracy                           :0.83
Precision of Positive cases                :0.74
Precision of Negative cases                :0.89
Positive Recall or TPR or Sensitivity      :0.82
Negative Recall or FPR or Specificity      :0.84


In [41]:
y_pred = model.predict(X_test)

In [42]:
print_scores(y_test, y_pred)

Overall Accuracy                           :0.77
Precision of Positive cases                :0.65
Precision of Negative cases                :0.83
Positive Recall or TPR or Sensitivity      :0.64
Negative Recall or FPR or Specificity      :0.84


In [43]:
confusion_matrix(y_test, y_pred)

array([[132,  25],
       [ 27,  47]], dtype=int64)

In [44]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.84      0.84       157
           1       0.65      0.64      0.64        74

    accuracy                           0.77       231
   macro avg       0.74      0.74      0.74       231
weighted avg       0.77      0.77      0.77       231



# Decision Tree Classifier

In [47]:
# PRINT TREE GENERATED BY DECISIONTREECLASSIFIER
from sklearn.tree import export_text
tree_rules = export_text(model, feature_names = list(X_train))
print(tree_rules)

|--- Glucose <= 144.50
|   |--- Age <= 28.50
|   |   |--- BMI <= 30.45
|   |   |   |--- Pregnancies <= 7.00
|   |   |   |   |--- DiabetesPedigreeFunction <= 0.67
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- DiabetesPedigreeFunction >  0.67
|   |   |   |   |   |--- class: 0
|   |   |   |--- Pregnancies >  7.00
|   |   |   |   |--- class: 1
|   |   |--- BMI >  30.45
|   |   |   |--- Glucose <= 127.50
|   |   |   |   |--- BloodPressure <= 53.00
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- BloodPressure >  53.00
|   |   |   |   |   |--- class: 0
|   |   |   |--- Glucose >  127.50
|   |   |   |   |--- BloodPressure <= 73.00
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- BloodPressure >  73.00
|   |   |   |   |   |--- class: 0
|   |--- Age >  28.50
|   |   |--- BMI <= 26.35
|   |   |   |--- Glucose <= 131.50
|   |   |   |   |--- class: 0
|   |   |   |--- Glucose >  131.50
|   |   |   |   |--- BMI <= 24.00
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- BMI 

# KNN

In [50]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
model = KNeighborsClassifier(n_neighbors = 5)
model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [55]:
y_pred_scaled = model.predict(X_train_scaled)

In [56]:
print_scores(y_train, y_pred_scaled)

Overall Accuracy                           :0.80
Precision of Positive cases                :0.77
Precision of Negative cases                :0.82
Positive Recall or TPR or Sensitivity      :0.65
Negative Recall or FPR or Specificity      :0.89


In [57]:
y_pred = model.predict(X_test_scaled)

In [58]:
print_scores(y_test, y_pred)

Overall Accuracy                           :0.75
Precision of Positive cases                :0.65
Precision of Negative cases                :0.78
Positive Recall or TPR or Sensitivity      :0.49
Negative Recall or FPR or Specificity      :0.88


# Naive Bayes

In [59]:
from sklearn.naive_bayes import GaussianNB

In [60]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [61]:
y_train_pred = model.predict(X_train)

In [62]:
print_scores(y_train, y_train_pred)

Overall Accuracy                           :0.74
Precision of Positive cases                :0.65
Precision of Negative cases                :0.78
Positive Recall or TPR or Sensitivity      :0.60
Negative Recall or FPR or Specificity      :0.82


In [64]:
y_pred = model.predict(X_test)

In [65]:
print_scores(y_test, y_pred)

Overall Accuracy                           :0.75
Precision of Positive cases                :0.65
Precision of Negative cases                :0.79
Positive Recall or TPR or Sensitivity      :0.50
Negative Recall or FPR or Specificity      :0.87


In [67]:
confusion_matrix(y_test,y_pred)

array([[137,  20],
       [ 37,  37]], dtype=int64)

In [68]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.87      0.83       157
           1       0.65      0.50      0.56        74

    accuracy                           0.75       231
   macro avg       0.72      0.69      0.70       231
weighted avg       0.74      0.75      0.74       231



In [69]:
print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       0.78      0.82      0.80       343
           1       0.65      0.60      0.62       194

    accuracy                           0.74       537
   macro avg       0.72      0.71      0.71       537
weighted avg       0.74      0.74      0.74       537



# Support Vector Machines

In [70]:
from sklearn.svm import SVC

In [71]:
model = SVC()
model.fit(X_train_scaled, y_train)

SVC()

In [73]:
y_train_pred = model.predict(X_train_scaled)

In [74]:
print_scores(y_train, y_train_pred)

Overall Accuracy                           :0.82
Precision of Positive cases                :0.81
Precision of Negative cases                :0.82
Positive Recall or TPR or Sensitivity      :0.65
Negative Recall or FPR or Specificity      :0.92


In [75]:
y_pred = model.predict(X_test_scaled)

In [76]:
print_scores(y_test, y_pred)

Overall Accuracy                           :0.74
Precision of Positive cases                :0.63
Precision of Negative cases                :0.76
Positive Recall or TPR or Sensitivity      :0.42
Negative Recall or FPR or Specificity      :0.89
